<a href="https://colab.research.google.com/github/thisismm08/-Predicting-Heart-Disease-with-Neural-Networks/blob/main/Heart_Disease_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predicting Heart Disease

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("http://storage.googleapis.com/download.tensorflow.org/data/heart.csv")

In [3]:
df.shape

(303, 14)

In [4]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,1,145,233,1,2,150,0,2.3,3,0,fixed,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,normal,1
2,67,1,4,120,229,0,2,129,1,2.6,2,2,reversible,0
3,37,1,3,130,250,0,0,187,0,3.5,3,0,normal,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,normal,0

Let's take a quick look to see if the 1s and 0s are balanced.

In [5]:
df.target.value_counts(normalize=True, dropna=False)

target
0    0.726073
1    0.273927
Name: proportion, dtype: float64

## Preprocessing

In [6]:
categorical_variables = ['sex', 'cp', 'fbs', 'restecg','exang', 'ca', 'thal']
numerics = ['age', 'trestbps','chol', 'thalach', 'oldpeak', 'slope']

In [7]:
df = pd.get_dummies(df, columns = categorical_variables)

In [8]:
df.head()

,age,trestbps,chol,thalach,oldpeak,slope,target,sex_0,sex_1,cp_0,...,exang_1,ca_0,ca_1,ca_2,ca_3,thal_1,thal_2,thal_fixed,thal_normal,thal_reversible
0,63,145,233,150,2.3,3,0,False,True,False,...,False,True,False,False,False,False,False,True,False,False
1,67,160,286,108,1.5,2,1,False,True,False,...,True,False,False,False,True,False,False,False,True,False
2,67,120,229,129,2.6,2,0,False,True,False,...,True,False,False,True,False,False,False,False,False,True
3,37,130,250,187,3.5,3,0,False,True,False,...,False,True,False,False,False,False,False,False,True,False
4,41,130,204,172,1.4,1,0,True,False,False,...,False,True,False,False,False,False,False,False,True,False

In [9]:
test_df = df.sample(frac=0.2, random_state=42)
train_df = df.drop(test_df.index)

In [10]:
train_df.shape

(242, 30)

In [11]:
test_df.shape

(61, 30)

In [12]:
means = train_df[numerics].mean()
sd = train_df[numerics].std()

In [13]:
means

age          54.268595
trestbps    131.995868
chol        246.512397
thalach     149.805785
oldpeak       1.032645
slope         1.590909
dtype: float64

In [14]:
train_df[numerics]= (train_df[numerics] - means)/sd

In [15]:
test_df[numerics]= (test_df[numerics] - means)/sd

In [16]:
train_df.head()

,age,trestbps,chol,thalach,oldpeak,slope,target,sex_0,sex_1,cp_0,...,exang_1,ca_0,ca_1,ca_2,ca_3,thal_1,thal_2,thal_fixed,thal_normal,thal_reversible
0,0.963746,0.721939,-0.278690,0.008396,1.083461,2.226814,0,False,True,False,...,False,True,False,False,False,False,False,True,False,False
1,1.405254,1.554681,0.814423,-1.807247,0.399542,0.646494,1,False,True,False,...,True,False,False,False,True,False,False,False,True,False
2,1.405254,-0.665964,-0.361189,-0.899426,1.339930,0.646494,0,False,True,False,...,True,False,False,True,False,False,False,False,False,True
3,-1.906055,-0.110803,0.071931,1.607891,2.109339,2.226814,0,False,True,False,...,False,True,False,False,False,False,False,False,True,False
4,-1.464547,-0.110803,-0.876809,0.959447,0.314052,-0.933825,0,True,False,False,...,False,True,False,False,False,False,False,False,True,False

In [24]:
train = train_df.to_numpy()
test = test_df.to_numpy()

In [25]:
train_X = np.delete(train, 6, axis=1)
test_X = np.delete(test, 6, axis=1)

In [26]:
train_X.shape, test_X.shape

((242, 29), (61, 29))

In [27]:
train_y = train[:, 6]
test_y = test[:, 6]

In [28]:
train_y.shape, test_y.shape

((242,), (61,))

## Build a model


### Define model in Keras

In [30]:
num_columns = train_X.shape[1]

input = keras.Input(shape= (num_columns,) )
h = keras.layers.Dense(16, activation="relu", name="Hidden")(input)
output = keras.layers.Dense(1, activation="sigmoid", name="Output")(h)
model = keras.Model(input, output)

In [31]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 29)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden (Dense)                  │ (None, 16)             │           480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output (Dense)                  │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 497 (1.94 KB)

 Trainable params: 497 (1.94 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])

In [48]:
import numpy as np
train_X_fixed = np.array(train_X).astype('float32')
train_y_fixed = np.array(train_y).astype('float32')

history = model.fit(
    train_X_fixed,
    train_y_fixed,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.3498 - loss: 0.7971 - val_accuracy: 0.3469 - val_loss: 0.7367
Epoch 2/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4367 - loss: 0.7241 - val_accuracy: 0.4694 - val_loss: 0.7062
Epoch 3/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5202 - loss: 0.6819 - val_accuracy: 0.5714 - val_loss: 0.6818
Epoch 4/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6529 - loss: 0.6439 - val_accuracy: 0.5918 - val_loss: 0.6610
Epoch 5/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6925 - loss: 0.6232 - val_accuracy: 0.5510 - val_loss: 0.6421
Epoch 6/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7531 - loss: 0.5881 - val_accuracy: 0.6531 - val_loss: 0.6273
Epoch 7/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7590 - loss: 0.5645 - val_accuracy: 0.6735 - val_loss: 0.6130
Epoch 8/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7288 - loss: 0.5515 - val_accuracy: 0.6735 - val_loss: 0.6025
Epoch 9/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.7669 - loss: 0.5228 - val_accuracy: 0.6735 - val_loss: 0.5902
Epoch 10/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7446 - loss: 0.5365 - val_accuracy: 0.6735 - val_loss: 0.5796

In [52]:
test_X_fixed = np.array(test_X).astype('float32')
test_y_fixed = np.array(test_y).astype('float32')

results = model.evaluate(test_X_fixed, test_y_fixed)

print(f"Test Loss: {results[0]}")
print(f"Test Accuracy: {results[1]}")

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7522 - loss: 0.5290
Test Loss: 0.5374568104743958
Test Accuracy: 0.7377049326896667